services:
  backend:
    build: ./backend
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "alembic upgrade head && uvicorn main:app --host=0.0.0.0 --port 8000 --log-level=info"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    networks:
      - nginx-proxy
      - infrastructure

  repeat_worker:
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "python3 run_repeat_worker.py"
    volumes:
      - ./backend:/backend
    environment:
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    networks:
      - nginx-proxy
      - infrastructure

  post_amo_lead_worker:
    build: ./backend
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "python3 run_amo_post_worker.py"
    volumes:
      - ./backend:/backend
    environment:
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    networks:
      - nginx-proxy
      - infrastructure

  backend_jobs:
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "python3 start_jobs.py"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      S3_URL: ${S3_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
    networks:
      - nginx-proxy

  teleg_bot:
    image: tablecrm_backend:latest
    restart: always
    command: python3 bot.py
    volumes:
      - ./backend:/backend
      - /photos:/backend/photos
    depends_on:
      - backend
    environment:
      APP_URL: ${APP_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    networks:
      - nginx-proxy
      - infrastructure

  message_consumer_task:
    build: ./backend
    restart: always
    command: python3 message_consumer.py
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TG_TOKEN: ${TG_TOKEN}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
    networks:
      - nginx-proxy
      - infrastructure

networks:
  nginx-proxy:
    name: tablecrm_nginx-proxy
    external: true
  infrastructure:
    name: infrastructure
    external: true
  shared_services:
    external: true