services:
  repeat_worker:
    build: ./backend
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "python3 run_repeat_worker.py"
    network_mode: host
    volumes:
      - ./backend:/backend
    environment:
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}

  backend:
    build: ./backend
    image: tablecrm_backend:latest
    restart: always
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && uvicorn main:app --host=0.0.0.0 --port 9000 --log-level=info --reload"
    network_mode: host
    volumes:
      - ./backend:/backend
      - /migrations:/backend/database/alembic/versions
    expose:
      - 9000
    environment:
      APP_URL: ${APP_URL}
      S3_ACCESS: ${S3_ACCESS}
      S3_SECRET: ${S3_SECRET}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      ACCOUNT_INTERVAL: ${ACCOUNT_INTERVAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      XDG_RUNTIME_DIR: ./tmp
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}

  teleg_bot:
    image: tablecrm_backend:latest
    restart: always
    command: python3 bot.py
    network_mode: host
    volumes:
      - ./backend:/backend
      - /photos:/backend/photos
    environment:
      APP_URL: ${APP_URL}
      TG_TOKEN: ${TG_TOKEN}
      CHEQUES_TOKEN: ${CHEQUES_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}